name = "rhemanotes"
main = "worker/seo-worker.ts"
compatibility_date = "2024-11-01"
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "rhemanotes-db"
database_id = "2a7e39cf-71ff-4b08-b7ea-36d7585d3575"
