/**
 * seoService.ts
 *
 * Generates and injects dynamic <head> metadata for RhemaNotes.
 *
 * Used in two places:
 *   1. React app  — call `setPageMeta()` on route/sermon changes
 *   2. Cloudflare Worker — call `buildSermonMetaHTML()` to inject into
 *      the HTML response before serving (for crawlers that don't run JS)
 */

const BASE_URL  = 'https://rhemanotes.biblefunland.com';
const OG_IMAGE  = `${BASE_URL}/og-image.png`;
const SITE_NAME = 'RhemaNotes';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface PageMeta {
  title: string;
  description: string;
  canonical: string;
  ogImage?: string;
  ogType?: 'website' | 'article';
  /** ISO 8601 date string — used for article published time */
  publishedAt?: string;
  /** Keywords specific to this page */
  keywords?: string[];
  /** JSON-LD object to inject — serialised automatically */
  jsonLd?: object;
}

// ── Preset metadata ───────────────────────────────────────────────────────────

export const HOME_META: PageMeta = {
  title: 'RhemaNotes — AI Sermon Notes, Bible Study & Scripture Summaries',
  description:
    'RhemaNotes turns any sermon into structured study notes, scripture links, flashcards, quizzes and reflections — instantly. The AI-powered Bible study companion for every Christian.',
  canonical: `${BASE_URL}/`,
  ogType: 'website',
  keywords: [
    'sermon notes', 'AI sermon summary', 'Bible study app',
    'sermon transcription', 'Christian notes app', 'Rhema', 'SpiritScribe',
    'church notes', 'scripture study', 'sermon flashcards',
  ],
  jsonLd: {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: SITE_NAME,
    url: BASE_URL,
    description: 'AI-powered sermon notes and Bible study tools for Christians.',
    applicationCategory: 'EducationApplication',
    operatingSystem: 'Web, iOS, Android',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    publisher: {
      '@type': 'Organization',
      name: SITE_NAME,
      logo: { '@type': 'ImageObject', url: OG_IMAGE }
    }
  }
};

export const HISTORY_META: PageMeta = {
  title: 'My Sermon History — RhemaNotes',
  description:
    'Browse all your saved sermon notes, scripture references and study guides on RhemaNotes.',
  canonical: `${BASE_URL}/history`,
  ogType: 'website',
  jsonLd: {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'My Sermon History',
    description: 'Archive of saved sermon notes and study guides.',
    publisher: { '@type': 'Organization', name: SITE_NAME }
  }
};

/**
 * Generates dynamic metadata for a single sermon note page.
 * Call this when a user opens a saved sermon.
 */
export function buildSermonMeta(sermon: {
  id: string;
  title: string;
  mainTopic: string;
  scriptureCount: number;
  timestamp: number;
}): PageMeta {
  const shortTitle =
    sermon.title.length > 60
      ? sermon.title.slice(0, 57) + '…'
      : sermon.title;

  const description =
    `"${shortTitle}" — ${sermon.scriptureCount} scripture reference${sermon.scriptureCount !== 1 ? 's' : ''} detected. ` +
    `Study notes, flashcards, quiz and Bible links generated by RhemaNotes AI.`;

  const canonical = `${BASE_URL}/note/${sermon.id}`;
  const publishedAt = new Date(sermon.timestamp).toISOString();

  return {
    title: `${shortTitle} — RhemaNotes`,
    description,
    canonical,
    ogType: 'article',
    publishedAt,
    keywords: [
      'sermon notes', sermon.title, sermon.mainTopic,
      'Bible study', 'scripture references', 'AI sermon summary',
    ],
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: sermon.title,
      description,
      url: canonical,
      datePublished: publishedAt,
      dateModified: publishedAt,
      author: {
        '@type': 'Organization',
        name: SITE_NAME,
        url: BASE_URL,
      },
      publisher: {
        '@type': 'Organization',
        name: SITE_NAME,
        url: BASE_URL,
        logo: {
          '@type': 'ImageObject',
          url: OG_IMAGE,
        },
      },
      image: OG_IMAGE,
      mainEntityOfPage: {
        '@type': 'WebPage',
        '@id': canonical,
      },
      keywords: `sermon notes, ${sermon.title}, ${sermon.mainTopic}, Bible study, scripture`,
      about: {
        '@type': 'Thing',
        name: sermon.mainTopic,
      },
    },
  };
}

// ── React head injection ──────────────────────────────────────────────────────

/**
 * Injects or updates <head> meta tags in the live React app.
 * Call this whenever the active "page" changes (home, history, sermon view).
 *
 * Usage:
 *   import { setPageMeta, HOME_META } from './services/seoService';
 *   useEffect(() => setPageMeta(HOME_META), []);
 */
export function setPageMeta(meta: PageMeta): void {
  // Title
  document.title = meta.title;

  setMeta('name', 'description', meta.description);
  setMeta('name', 'keywords', (meta.keywords ?? []).join(', '));
  setLink('canonical', meta.canonical);

  // Open Graph
  setMeta('property', 'og:title',       meta.title);
  setMeta('property', 'og:description', meta.description);
  setMeta('property', 'og:url',         meta.canonical);
  setMeta('property', 'og:type',        meta.ogType ?? 'website');
  setMeta('property', 'og:image',       meta.ogImage ?? OG_IMAGE);
  setMeta('property', 'og:site_name',   SITE_NAME);

  if (meta.ogType === 'article' && meta.publishedAt) {
    setMeta('property', 'article:published_time', meta.publishedAt);
    setMeta('property', 'article:modified_time',  meta.publishedAt);
    setMeta('property', 'article:section',        'Religion & Spirituality');
  }

  // Twitter
  setMeta('name', 'twitter:title',       meta.title);
  setMeta('name', 'twitter:description', meta.description);
  setMeta('name', 'twitter:image',       meta.ogImage ?? OG_IMAGE);

  // JSON-LD
  if (meta.jsonLd) {
    let el = document.getElementById('dynamic-jsonld') as HTMLScriptElement | null;
    if (!el) {
      el = document.createElement('script');
      el.id   = 'dynamic-jsonld';
      el.type = 'application/ld+json';
      document.head.appendChild(el);
    }
    el.textContent = JSON.stringify(meta.jsonLd, null, 2);
  }
}

function setMeta(attr: 'name' | 'property', key: string, value: string): void {
  if (!value) return;
  let el = document.querySelector<HTMLMetaElement>(`meta[${attr}="${key}"]`);
  if (!el) {
    el = document.createElement('meta');
    el.setAttribute(attr, key);
    document.head.appendChild(el);
  }
  el.setAttribute('content', value);
}

function setLink(rel: string, href: string): void {
  let el = document.querySelector<HTMLLinkElement>(`link[rel="${rel}"]`);
  if (!el) {
    el = document.createElement('link');
    el.rel = rel;
    document.head.appendChild(el);
  }
  el.href = href;
}

// ── Cloudflare Worker HTML builder ────────────────────────────────────────────

/**
 * Builds a complete <head> block string for server-side injection.
 *
 * Use this in your Cloudflare Worker to replace the static <head> in
 * index.html with dynamic metadata before serving to crawlers.
 *
 * See: worker/seo-worker.ts for the full Worker implementation.
 */
export function buildMetaHTML(meta: PageMeta): string {
  const kw = (meta.keywords ?? HOME_META.keywords ?? []).join(', ');
  const img = meta.ogImage ?? OG_IMAGE;
  const type = meta.ogType ?? 'website';

  const articleTags = type === 'article' && meta.publishedAt ? `
  <meta property="article:published_time" content="${meta.publishedAt}" />
  <meta property="article:modified_time"  content="${meta.publishedAt}" />
  <meta property="article:section"        content="Religion &amp; Spirituality" />` : '';

  const jsonLdTag = meta.jsonLd
    ? `\n  <script type="application/ld+json">\n  ${JSON.stringify(meta.jsonLd, null, 2)}\n  </script>`
    : '';

  return `
  <!-- RhemaNotes SEO — generated by seoService -->
  <title>${escapeHtml(meta.title)}</title>
  <meta name="description" content="${escapeHtml(meta.description)}" />
  <meta name="keywords"    content="${escapeHtml(kw)}" />
  <meta name="robots"      content="index, follow, max-snippet:-1, max-image-preview:large" />
  <link rel="canonical"    href="${meta.canonical}" />

  <meta property="og:type"        content="${type}" />
  <meta property="og:site_name"   content="${SITE_NAME}" />
  <meta property="og:title"       content="${escapeHtml(meta.title)}" />
  <meta property="og:description" content="${escapeHtml(meta.description)}" />
  <meta property="og:url"         content="${meta.canonical}" />
  <meta property="og:image"       content="${img}" />
  <meta property="og:image:width"  content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:alt"   content="${escapeHtml(meta.title)}" />${articleTags}

  <meta name="twitter:card"        content="summary_large_image" />
  <meta name="twitter:site"        content="@RhemaNotes" />
  <meta name="twitter:title"       content="${escapeHtml(meta.title)}" />
  <meta name="twitter:description" content="${escapeHtml(meta.description)}" />
  <meta name="twitter:image"       content="${img}" />${jsonLdTag}`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
