import React from 'react';
import { BookOpen, Shield, ArrowLeft } from 'lucide-react';

interface LegalPageProps {
  onBack: () => void;
}

export const TermsOfService: React.FC<LegalPageProps> = ({ onBack }) => {
  const updated = 'May 3, 2026';
  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <button onClick={onBack} className="flex items-center space-x-2 text-indigo-900/50 hover:text-indigo-900 mb-8 font-bold text-sm">
        <ArrowLeft className="w-4 h-4" /><span>Back</span>
      </button>
      <div className="flex items-center space-x-3 mb-2">
        <BookOpen className="w-7 h-7 text-indigo-900" />
        <h1 className="text-3xl font-serif font-black text-indigo-950">Terms of Service</h1>
      </div>
      <p className="text-sm text-indigo-900/40 mb-10">Last updated: {updated}</p>

      <div className="prose prose-indigo max-w-none space-y-8 text-indigo-900/80 leading-relaxed">
        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using RhemaNotes ("the Service") at rhemanotes.biblefunland.com, you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. RhemaNotes is a product of BibleFunLand.com.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">2. Description of Service</h2>
          <p>RhemaNotes is an AI-powered sermon note-taking and Bible study application. It allows users to submit sermon audio, video links, or text and receive AI-generated summaries, scripture references, flashcards, and study tools.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">3. User Accounts</h2>
          <p>You must create an account to use certain features. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information during registration.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">4. Subscription and Payments</h2>
          <p>RhemaNotes offers free and paid subscription tiers ("The Seed," "The Vine," and "The Harvest"). Paid subscriptions are billed through Stripe. By subscribing, you authorize us to charge your payment method on a recurring basis. You may cancel at any time through your account settings. Refunds are handled at our discretion.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">5. Acceptable Use</h2>
          <p>You agree not to use the Service to: (a) submit copyrighted sermon content you do not have rights to process; (b) attempt to reverse-engineer or abuse the AI system; (c) transmit harmful, offensive, or unlawful content; (d) violate any applicable laws or regulations.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">6. AI-Generated Content</h2>
          <p>Content generated by RhemaNotes AI is for personal study and reference only. It should not replace direct engagement with Scripture or pastoral guidance. We do not guarantee the theological accuracy of AI-generated content.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">7. Intellectual Property</h2>
          <p>The RhemaNotes platform, its design, and technology are owned by BibleFunLand.com. User-submitted content remains the property of the user. By submitting content, you grant us a limited license to process it for the purpose of providing the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">8. Termination</h2>
          <p>We reserve the right to suspend or terminate your account at any time for violation of these Terms or for any other reason at our sole discretion.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">9. Disclaimer of Warranties</h2>
          <p>The Service is provided "as is" without warranties of any kind. We do not guarantee uninterrupted or error-free service. Use of AI-generated biblical content is at your own discretion.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">10. Contact</h2>
          <p>For questions about these Terms, contact us at: <a href="mailto:support@biblefunland.com" className="text-indigo-600 underline">support@biblefunland.com</a></p>
        </section>
      </div>
    </div>
  );
};

export const PrivacyPolicy: React.FC<LegalPageProps> = ({ onBack }) => {
  const updated = 'May 3, 2026';
  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <button onClick={onBack} className="flex items-center space-x-2 text-indigo-900/50 hover:text-indigo-900 mb-8 font-bold text-sm">
        <ArrowLeft className="w-4 h-4" /><span>Back</span>
      </button>
      <div className="flex items-center space-x-3 mb-2">
        <Shield className="w-7 h-7 text-indigo-900" />
        <h1 className="text-3xl font-serif font-black text-indigo-950">Privacy Policy</h1>
      </div>
      <p className="text-sm text-indigo-900/40 mb-10">Last updated: {updated}</p>

      <div className="prose prose-indigo max-w-none space-y-8 text-indigo-900/80 leading-relaxed">
        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">1. Information We Collect</h2>
          <p>We collect the following personal information when you use RhemaNotes:</p>
          <ul className="list-disc ml-6 space-y-1 mt-2">
            <li><strong>Account information</strong>: Name, email address (via Clerk authentication)</li>
            <li><strong>Payment information</strong>: Billing details processed by Stripe (we never store card numbers)</li>
            <li><strong>Usage data</strong>: Sermon submissions, summaries, and study notes stored in our database</li>
            <li><strong>Technical data</strong>: IP address, browser type, and device information</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">2. How We Use Your Information</h2>
          <p>We use your information to:</p>
          <ul className="list-disc ml-6 space-y-1 mt-2">
            <li>Provide and improve the RhemaNotes service</li>
            <li>Process payments and manage subscriptions</li>
            <li>Send service-related communications (no marketing without consent)</li>
            <li>Ensure account security and prevent fraud</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">3. AI Processing</h2>
          <p>Sermon content you submit is sent to Google's Gemini AI API for processing. We do not use your sermon content to train AI models. Content is processed solely to generate your study notes and is stored in your personal account only.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">4. Third-Party Services</h2>
          <ul className="list-disc ml-6 space-y-1 mt-2">
            <li><strong>Clerk</strong>: Handles authentication. See <a href="https://clerk.com/privacy" target="_blank" className="text-indigo-600 underline">Clerk Privacy Policy</a></li>
            <li><strong>Stripe</strong>: Handles payment processing. See <a href="https://stripe.com/privacy" target="_blank" className="text-indigo-600 underline">Stripe Privacy Policy</a></li>
            <li><strong>Cloudflare</strong>: Hosts the application. See <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" className="text-indigo-600 underline">Cloudflare Privacy Policy</a></li>
            <li><strong>Google Gemini</strong>: Processes sermon content for AI summaries</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">5. Data Storage & Security</h2>
          <p>Your data is stored in Cloudflare D1 (SQLite) databases hosted in Cloudflare's secure infrastructure. We implement industry-standard security measures including encrypted connections (HTTPS) and secure secret management.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">6. Your Rights</h2>
          <p>You have the right to:</p>
          <ul className="list-disc ml-6 space-y-1 mt-2">
            <li>Access the personal data we hold about you</li>
            <li>Request deletion of your account and data</li>
            <li>Export your sermon notes and study data</li>
            <li>Opt out of any non-essential communications</li>
          </ul>
          <p className="mt-2">To exercise these rights, email us at <a href="mailto:privacy@biblefunland.com" className="text-indigo-600 underline">privacy@biblefunland.com</a></p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">7. Children's Privacy</h2>
          <p>RhemaNotes is not intended for children under 13. We do not knowingly collect personal information from children under 13. If you believe a child has provided us with personal information, please contact us immediately.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">8. Changes to This Policy</h2>
          <p>We may update this Privacy Policy from time to time. We will notify users of significant changes via email or a notice on the app. Continued use of the Service after changes constitutes acceptance of the updated policy.</p>
        </section>

        <section>
          <h2 className="text-xl font-black text-indigo-950 mb-2">9. Contact Us</h2>
          <p>For privacy-related questions: <a href="mailto:privacy@biblefunland.com" className="text-indigo-600 underline">privacy@biblefunland.com</a></p>
        </section>
      </div>
    </div>
  );
};
